# -*- coding: utf-8 -*-
"""Christian_Loeza-Cesar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJN1V5MsNhNuidQKdCPAaEV73xzkhH78

# Algoritmo de Cesar

---
uso de alfabeto de 27 caracteres
"""

alphabet = "abcdefghijklmnñopqrstuvwxyz"
alphabet_upper = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"

"""# Cifrado (Cesar)

`C = M + [k mod |A|]`
"""

message = input("Ingrese la frase a cifrar: ")
key = int(input("Ingrese la llave de cifrado: "))
alpha = len(alphabet)

def getIdM(m, i = 0):
  return alphabet.find(m[i])

def cesar(m, k, a):
  aN = []

  for i in range(len(m)):
    aN.append(getIdM(m, i) + (k % a))
  
  return aN

def toStr(arr, a, alpha):
  arrC = []

  for i in range(len(arr)):
    arrC.append(a[arr[i] % alpha])
  
  cad = "".join(arrC)

  return cad

cesarArr = cesar(message, key, alpha)

cesarStr = toStr(cesarArr, alphabet, alpha)

print(f"cesar (cifrado): {cesarStr}")

"""# Descifrado (Cesar)

`M = C - [k mod |A|]`
"""

cesarText = input("Ingrese la frase a descifrar: ")
key = int(input("Ingrese la llave de descifrado: "))
alpha = len(alphabet)

def getIdM(m, i = 0):
  return alphabet.find(m[i])

def message(m, k, a):
  arrN = []

  for i in range(len(m)):
    arrN.append(getIdM(m, i) - (k % a))
  
  return arrN

def toStr(arr, a):
  arrM = []

  for i in range(len(arr)):
    arrM.append(a[arr[i]])
  
  cad = "".join(arrM)

  return cad

messageArr = message(cesarText, key, alpha)

messageStr = toStr(messageArr, alphabet)

print(f"cesar (descifrado): {messageStr}")